### ISSUE TITLE
Missing library path on OpenBSD

### ISSUE THREAD

**Issue by ilylily** [vberger/dlib#15]
hi! thanks for dlib <3

i'm unable to build the following example code, stripped down from [smithay-client-toolkit's ffi.rs](https://github.com/Smithay/client-toolkit/blob/master/src/seat/keyboard/ffi.rs), on OpenBSD:

```rust
dlib::external_library!(XkbCommon, "xkbcommon", functions:
    fn xkb_keysym_to_utf32(u32) -> u32,
);

fn main() {
    println!("hey, it compiled ;p\nlook, a u32! should be 0: {}",
        unsafe { xkb_keysym_to_utf32(1) }
    );
}
```

Cargo.toml only requires `dlib`:

```toml
[package]
name = "dlib-minimal-example"
version = "0.1.0"
edition = "2018"

[dependencies]
dlib = "0.5"
```

i see the error `ld: error: unable to find library -lxkbcommon`. using `cargo run -v` to print the `rustc` line and re-running that line with `-L native=/usr/local/lib` at the end results in a successful build. it builds without any intervention on my Arch Linux machine, where xkbcommon is installed to `/usr/lib`

how can i ensure that `/usr/local/lib` (the default path for libraries from installed ports/packages on OpenBSD) is included in the native library search path?

this error causes a failure when compiling [iced](https://github.com/hecrj/iced), by way of [smithay-client-toolkit](https://github.com/smithay/client-toolkit), which is required by iced dependencies [winit](https://github.com/rust-windowing/winit) and [window_clipboard](https://github.com/hecrj/window_clipboard)

**Comment by vberger** [comment]
It looks like this error comes from rustc directly, rather than dlib.

Your above code should expand to the following:

```rust
#[link(name = "xkbcommon")]
extern "C" {
    fn xkb_keysym_to_utf32(u32) -> u32;
}

fn main() {
    println!("hey, it compiled ;p\nlook, a u32! should be 0: {}",
        unsafe { xkb_keysym_to_utf32(1) }
    );
}
```

Does that snippet of code also fails to compile with the same error? If yes, then this is likely an issue with rustc itself (or your installation of it), which does not look for libraries in the usual places of your platform.

**Comment by ilylily** [comment]
ah, that's it. the default library path does include `/usr/local/lib`, and adding it `LD_LIBRARY_PATH` doesn't do the trick, so i guess i'll do more testing and possibly contact the rustc package maintainer. thanks for the help!
