### ISSUE TITLE
Outdated dependency

### ISSUE THREAD

**Issue by pmarcelll** [vberger/dlib#8]
I noticed during building an application that uses `winit`, that `serde_json` 0.9.10 (which is pre-1.0 and no longer supported) is still used by `libloading` 0.3.4 (currently used by this crate). `libloading` 0.4.0 no longer requires the now deprecated `target_build_utils` crate (the API hasn't changed AFAICT), so the old `serde_json` version is no longer used, but `libloading` 0.4 requires at least rustc 1.14. According to crates.io, the main users of this crate is the various Wayland-related crates and `winit`, so updating `libloading` means for most of the GUI related stuff rustc 1.14 (released in last december) is a new minimal requirement. Is it acceptable?

**Comment by vberger** [comment]
The wayland-rs libs already depend on features that are newer than (and thus already do not compile on 1.14). So I see no issue with that.

Though this is a good point, I should find out what is the minimal rust version they depend on a test this on travis.

**Comment by vberger** [comment]
Released 0.4. Will update wayland-client and wayland-server too.
